import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { CircleMarker, MapContainer, Marker, Popup, TileLayer } from 'react-leaflet'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import './App.css'

const apiUrl = import.meta.env.VITE_API_URL ?? 'http://localhost:8000'
type Option = { id: number; name: string; city?: string; diagnosis?: string; services?: string[]; latitude?: number; longitude?: number; emergency_capable?: boolean }
type Options = { patients: Option[]; policies: Option[]; hospitals: Option[] }
type Part = { score: number; max: number; matched: boolean; distance_km?: number | null }
type Result = { hospital_name: string; total_score: number; score_breakdown: Record<string, Part>; matched_conditions: string[]; failed_conditions: string[]; warnings: string[]; explanation: string }
type Journey = { id: number; title: string; condition: string; events: { id: number; title: string; event_type: string; occurred_on: string; status: string }[] }
type Pathway = { hospital: string; compatibility_score: number; policy_compatibility: Part; financial: Record<string, { value: number | null; status: string }>; policy_risks: string[]; possible_policy_shocks: unknown[] }
type EmergencyHospital = { hospital_id: number; hospital_name: string; city: string; latitude: number; longitude: number; emergency_capable: boolean; distance_km: number | null; compatibility_score: number; policy_compatibility: Part; emergency_rank?: number }
type MapHospital = { hospital_id: number; hospital_name: string; city: string; latitude: number; longitude: number; emergency_capable: boolean; distance_km?: number | null; compatibility_score?: number; policy_compatibility?: Part; emergency_rank?: number }
const nav = [['/assessment', '01', 'Care Assessment'], ['/hospitals', '02', 'Hospital Matches'], ['/hospitals/detail', '03', 'Decision Evidence'], ['/compare', '04', 'Compare Pathways'], ['/journey', '05', 'Care Journey'], ['/copilot', '06', 'Caregiver Copilot']] as const

function App() {
  const [route, setRoute] = useState(location.pathname || '/assessment'), [menu, setMenu] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [options, setOptions] = useState<Options>({ patients: [], policies: [], hospitals: [] }), [patient, setPatient] = useState(''), [policy, setPolicy] = useState(''), [hospital, setHospital] = useState('')
  const [specialty, setSpecialty] = useState('oncology'), [service, setService] = useState('oncology'), [emergency, setEmergency] = useState(false), [result, setResult] = useState<Result | null>(null), [ranking, setRanking] = useState<Result[]>([])
  const [journey, setJourney] = useState<Journey | null>(null), [selected, setSelected] = useState<number[]>([]), [simulation, setSimulation] = useState<Pathway[]>([]), [simulationNote, setSimulationNote] = useState('')
  const [emergencyHospitals, setEmergencyHospitals] = useState<EmergencyHospital[]>([]), [emergencySelection, setEmergencySelection] = useState<EmergencyHospital | null>(null), [question, setQuestion] = useState('Why was this hospital recommended?'), [answer, setAnswer] = useState(''), [evidence, setEvidence] = useState<unknown[]>([])
  const go = (next: string) => { history.pushState({}, '', next); setRoute(next); setMenu(false) }
  useEffect(() => { const pop = () => setRoute(location.pathname || '/assessment'); addEventListener('popstate', pop); return () => removeEventListener('popstate', pop) }, [])
  useEffect(() => { fetch(`${apiUrl}/api/compatibility/options`).then((r) => { if (!r.ok) throw Error(); return r.json() }).then((data: Options) => { setOptions(data); setPatient(String(data.patients[0]?.id ?? '')); setPolicy(String(data.policies[0]?.id ?? '')); setHospital(String(data.hospitals[0]?.id ?? '')); setSelected(data.hospitals.slice(0, 2).map((item) => item.id)); if (data.patients[0]) loadJourney(data.patients[0].id) }).catch(() => setError('The API is unavailable. Start the backend on port 8000.')).finally(() => setLoading(false)) }, [])
  async function loadJourney(id: number) { try { const list = await (await fetch(`${apiUrl}/api/journeys?patient_id=${id}`)).json(); setJourney(list.journeys[0] ? await (await fetch(`${apiUrl}/api/journeys/${list.journeys[0].id}`)).json() : null) } catch { setError('The care journey could not be loaded.') } }
  const requirement = { specialty, service, emergency, max_distance_km: 50 }
  async function calculate(event: FormEvent) { event.preventDefault(); if (!patient || !policy || !hospital || !specialty.trim() || !service.trim()) return setError('Complete every care requirement field before calculating.'); const body = JSON.stringify({ patient_id: +patient, policy_id: +policy, hospital_id: +hospital, care_requirement: requirement }); try { const responses = await Promise.all(['/api/compatibility/score', '/api/compatibility/rank'].map((url) => fetch(apiUrl + url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body }))); if (responses.some((r) => !r.ok)) throw Error(); setResult(await responses[0].json()); setRanking((await responses[1].json()).results); go('/hospitals') } catch { setError('Compatibility calculation failed. Check that the backend and database are running.') } }
  async function loadEmergency() { const response = await fetch(`${apiUrl}/api/emergency/rank`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ patient_id: +patient, policy_id: +policy, care_requirement: { ...requirement, emergency: true, latitude: 28.4595, longitude: 77.0266 } }) }); if (response.ok) { const data = await response.json(); setEmergencyHospitals(data.results); setEmergencySelection(data.results[0] ?? null) } else setError('Emergency ranking failed.') }
  async function compare(event: FormEvent) { event.preventDefault(); if (selected.length < 2) return setError('Select at least two hospitals to compare.'); const response = await fetch(`${apiUrl}/api/simulations/compare`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ patient_id: +patient, policy_id: +policy, hospital_ids: selected, journey_id: journey?.id ?? null, care_requirement: requirement }) }); if (response.ok) { const data = await response.json(); setSimulation(data.pathways); setSimulationNote(data.data_quality_note) } else setError('The comparison could not be created.') }
  async function ask(event: FormEvent) { event.preventDefault(); const response = await fetch(`${apiUrl}/api/copilot/ask`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, patient_id: +patient, policy_id: +policy, hospital_id: +hospital, journey_id: journey?.id, care_requirement: requirement }) }); if (response.ok) { const data = await response.json(); setAnswer(data.answer); setEvidence(data.evidence) } else setError('The caregiver copilot could not retrieve the selected data.') }
  if (loading) return <main className="loading-page">Loading CogniCare records...</main>
  const current = nav.find((item) => item[0] === route) ?? nav[0]
  return <div className="app-shell"><aside className={`sidebar ${menu ? 'open' : ''}`}><div className="brand"><strong>CogniCare</strong><span>Decision Intelligence</span></div><nav>{nav.map(([href, number, label]) => <button className={current[0] === href ? 'active' : ''} key={href} onClick={() => go(href)}><span>{number}</span>{label}</button>)}</nav><div className="sidebar-footer"><button>Settings</button><small><i /> System status: online</small></div></aside>{menu && <button className="drawer-backdrop" onClick={() => setMenu(false)} aria-label="Close navigation" />}<main className="workspace"><header className="topbar"><button className="menu-button" onClick={() => setMenu(true)} aria-label="Open navigation">☰</button><div><span className="eyebrow">COGNICARE / {current[1]}</span><h1>{current[2]}</h1><p>{route === '/assessment' ? 'Build a care requirement from patient needs, policy rules, and practical access.' : 'A focused view of the care decision and its supporting evidence.'}</p></div><div className="top-actions"><span className="engine-status"><i /> Engine online</span><button className="emergency-button" onClick={() => { loadEmergency(); go('/emergency') }}>Emergency care</button></div></header>{error && <div className="error">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}{route === '/assessment' && <Assessment options={options} patient={patient} policy={policy} hospital={hospital} specialty={specialty} service={service} emergency={emergency} setPatient={setPatient} setPolicy={setPolicy} setHospital={setHospital} setSpecialty={setSpecialty} setService={setService} setEmergency={setEmergency} calculate={calculate} />}{route === '/hospitals' && <Hospitals options={options} ranking={ranking} result={result} navigate={go} emergencyHospitals={emergencyHospitals} selected={emergencySelection} select={(item) => setEmergencySelection(item as EmergencyHospital)} load={loadEmergency} setResult={setResult} />}{route === '/hospitals/detail' && <Decision result={result} navigate={go} />}{route === '/compare' && <Compare options={options} selected={selected} setSelected={setSelected} simulation={simulation} note={simulationNote} compare={compare} />}{route === '/journey' && <JourneyView journey={journey} />}{route === '/copilot' && <Copilot question={question} setQuestion={setQuestion} answer={answer} evidence={evidence} ask={ask} />}{route === '/emergency' && <Emergency hospitals={emergencyHospitals} selected={emergencySelection} select={setEmergencySelection} load={loadEmergency} />}</main></div>
}
function Assessment({ options, patient, policy, hospital, specialty, service, emergency, setPatient, setPolicy, setHospital, setSpecialty, setService, setEmergency, calculate }: { options: Options; patient: string; policy: string; hospital: string; specialty: string; service: string; emergency: boolean; setPatient: (v: string) => void; setPolicy: (v: string) => void; setHospital: (v: string) => void; setSpecialty: (v: string) => void; setService: (v: string) => void; setEmergency: (v: boolean) => void; calculate: (e: FormEvent) => void }) { return <section className="page-content"><div className="intro"><span className="step">01 / ASSESS</span><h2>Find the care fit.</h2><p>Choose a patient, policy, and care context to calculate a transparent hospital match.</p></div><form className="assessment-panel" onSubmit={calculate}><Field label="Patient"><select value={patient} onChange={(e) => setPatient(e.target.value)}>{options.patients.map((x) => <option key={x.id} value={x.id}>{x.name}{x.diagnosis ? ` / ${x.diagnosis}` : ''}</option>)}</select></Field><Field label="Policy"><select value={policy} onChange={(e) => setPolicy(e.target.value)}>{options.policies.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Starting hospital"><select value={hospital} onChange={(e) => setHospital(e.target.value)}>{options.hospitals.map((x) => <option key={x.id} value={x.id}>{x.name} / {x.city}</option>)}</select></Field><Field label="Required specialty"><input required value={specialty} onChange={(e) => setSpecialty(e.target.value)} placeholder="e.g. oncology" /></Field><Field label="Required service"><input required value={service} onChange={(e) => setService(e.target.value)} placeholder="e.g. infusion" /></Field><label className="toggle"><input type="checkbox" checked={emergency} onChange={(e) => setEmergency(e.target.checked)} /> Emergency capability required</label><button className="primary" type="submit">Calculate compatibility <span>→</span></button></form></section> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label>{label}{children}</label> }
function Hospitals({ options, ranking, result, navigate, emergencyHospitals, selected, select, load, setResult }: { options: Options; ranking: Result[]; result: Result | null; navigate: (x: string) => void; emergencyHospitals: EmergencyHospital[]; selected: EmergencyHospital | null; select: (x: EmergencyHospital) => void; load: () => void; setResult: (item: Result) => void }) { const mapHospitals: MapHospital[] = emergencyHospitals.length ? emergencyHospitals : options.hospitals.filter((x): x is Option & { latitude: number; longitude: number; city: string } => typeof x.latitude === 'number' && typeof x.longitude === 'number' && typeof x.city === 'string').map((x) => ({ hospital_id: x.id, hospital_name: x.name, city: x.city, latitude: x.latitude, longitude: x.longitude, emergency_capable: Boolean(x.emergency_capable) })); return <section className="page-content"><PageHeading step="02 / MATCH" title="Hospital matches" text="Ranked by policy fit, required care, emergency capability, and distance." action={<button className="secondary" onClick={load}>Refresh map</button>} /><div className="match-layout"><div className="hospital-list">{ranking.length ? ranking.map((x, i) => <button className={`hospital-card ${x.hospital_name === result?.hospital_name ? 'selected' : ''}`} key={x.hospital_name} onClick={() => { setResult(x); navigate('/hospitals/detail') }}><span className="rank-number">0{i + 1}</span><div><h3>{x.hospital_name}</h3><p>{x.explanation}</p><div className="card-meta"><b>{x.total_score} / 100</b><span>Policy fit {x.score_breakdown.policy_compatibility.score}/{x.score_breakdown.policy_compatibility.max}</span><span>{x.matched_conditions.length} matched</span></div></div></button>) : <Empty text="Calculate a care requirement to see hospital matches." />}</div><div className="map-panel"><MapView hospitals={mapHospitals} selected={selected} select={(item) => select(item as EmergencyHospital)} /></div></div></section> }
function MapView({ hospitals, selected, select }: { hospitals: MapHospital[]; selected: MapHospital | null; select: (x: MapHospital) => void }) { const bestScore = Math.max(...hospitals.map((x) => x.compatibility_score ?? 0), 0); return <MapContainer className="map" center={[28.52, 77.18]} zoom={10} scrollWheelZoom={false}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{hospitals.map((x) => { const isBest = (x.compatibility_score ?? 0) === bestScore && bestScore > 0; const isSelected = x.hospital_id === selected?.hospital_id; const markerIcon = L.divIcon({ className: `hospital-marker ${isBest ? 'best' : ''} ${isSelected ? 'selected' : ''}`, html: `<span>${isBest ? '★' : '•'}</span><b>${x.hospital_name}</b>`, iconAnchor: [10, 10] }); return <span key={x.hospital_id}><CircleMarker center={[x.latitude, x.longitude]} radius={isSelected ? 14 : 9} pathOptions={{ color: isBest ? '#17251f' : x.emergency_capable ? '#328052' : '#ec704b', fillColor: isBest ? '#b8e7c8' : '#ec704b', fillOpacity: .95, weight: isBest ? 3 : 2 }} eventHandlers={{ click: () => select(x) }}><Popup><strong>{x.hospital_name}</strong><br />{x.city}<br />{isBest ? 'Best current match' : 'Hospital match'}<br />Emergency: {x.emergency_capable ? 'Yes' : 'No'}{x.distance_km !== undefined ? <><br />Distance: {x.distance_km ?? 'Unavailable'} km</> : null}{x.compatibility_score !== undefined ? <><br />Score: {x.compatibility_score}/100</> : null}</Popup></CircleMarker><Marker position={[x.latitude, x.longitude]} icon={markerIcon} interactive={false} /></span> })}</MapContainer> }
function PageHeading({ step, title, text, action }: { step: string; title: string; text: string; action?: React.ReactNode }) { return <div className="page-heading"><div><span className="step">{step}</span><h2>{title}</h2><p>{text}</p></div>{action}</div> }
function Decision({ result, navigate }: { result: Result | null; navigate: (x: string) => void }) { if (!result) return <section className="page-content"><Empty text="Select a hospital from Hospital Matches to view decision evidence." /></section>; const scoreLabels: Record<string, string> = { network_compatibility: 'Network compatibility', required_specialty: 'Required specialty', required_service: 'Required service', policy_compatibility: 'Policy compatibility', emergency_capability: 'Emergency capability', distance: 'Distance & access' }; return <section className="page-content"><div className="decision-hero"><div><span className="step">03 / UNDERSTAND</span><h2>{result.hospital_name}</h2><p>{result.explanation}</p></div><strong className="large-score">{result.total_score}<small>/ 100</small></strong></div><div className="decision-grid"><section className="surface score-breakdown"><div className="section-title"><div><span className="eyebrow">COMPATIBILITY MODEL</span><h3>Score breakdown</h3></div><span className="score-legend">6 weighted conditions</span></div>{Object.entries(result.score_breakdown).map(([key, x]) => <div className="metric" key={key}><div className="metric-label"><span className={`metric-icon ${x.matched ? 'is-match' : 'is-fail'}`}>{x.matched ? '✓' : '!'}</span><span>{scoreLabels[key] ?? key.replaceAll('_', ' ')}</span><b>{x.score} / {x.max}</b></div><div className="bar"><i style={{ width: `${x.max ? x.score / x.max * 100 : 0}%` }} /></div><small>{x.matched ? 'Condition matched' : 'Needs review'}</small></div>)}</section><section className="surface evidence"><h3>Decision evidence</h3>{[['Matched', result.matched_conditions, 'match'], ['Failed', result.failed_conditions, 'fail'], ['Warnings', result.warnings, 'warning']].map(([title, items, tone]) => Array.isArray(items) && items.length ? <div className="evidence-group" key={String(title)}><h4>{String(title)}</h4>{items.map((item) => <div className={`evidence-item ${tone}`} key={item}><b>{tone === 'match' ? '✓' : tone === 'fail' ? '×' : '!'}</b>{item}</div>)}</div> : null)}</section></div><div className="action-row"><button className="primary" onClick={() => navigate('/compare')}>Compare hospitals <span>→</span></button><button className="secondary" onClick={() => navigate('/journey')}>Open care journey</button></div></section> }
function Compare({ options, selected, setSelected, simulation, note, compare }: { options: Options; selected: number[]; setSelected: (f: (x: number[]) => number[]) => void; simulation: Pathway[]; note: string; compare: (e: FormEvent) => void }) { return <section className="page-content"><PageHeading step="04 / COMPARE" title="Compare pathways" text="Compare the same care requirement across two to four hospitals." /><form className="compare-form"><div className="hospital-picks">{options.hospitals.map((x) => <label className={`pick ${selected.includes(x.id) ? 'checked' : ''}`} key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={() => setSelected((current) => current.includes(x.id) ? current.filter((id) => id !== x.id) : current.length < 4 ? [...current, x.id] : current)} /><span><b>{x.name}</b><small>{x.city} / {(x.services ?? []).join(', ')}</small></span></label>)}</div><p className="field-note">{selected.length < 2 ? 'Select at least two hospitals to enable comparison.' : `${selected.length} hospitals selected.`}</p><button className="primary" disabled={selected.length < 2} onClick={compare}>Compare selected pathways <span>→</span></button></form>{simulation.length > 0 && <section className="surface comparison-result"><p className="simulation-note">{note}</p><div className="comparison-chart">{simulation.map((x) => <div className="chart-column" key={x.hospital}><strong>{x.compatibility_score}</strong><i style={{ height: `${x.compatibility_score}%` }} /><span>{x.hospital}</span></div>)}</div><div className="table-wrap"><table><thead><tr><th>Hospital</th><th>Score</th><th>Policy fit</th><th>Total cost</th><th>Insurance</th><th>Patient payment</th><th>Risks</th></tr></thead><tbody>{simulation.map((x) => <tr key={x.hospital}><th>{x.hospital}</th><td>{x.compatibility_score}/100</td><td>{x.policy_compatibility.score}/{x.policy_compatibility.max}</td>{['total_cost', 'insurance_coverage', 'patient_payment'].map((key) => <td key={key}>{x.financial[key].value === null ? 'Unavailable' : `$${x.financial[key].value}`}<small>{x.financial[key].status}</small></td>)}<td>{x.policy_risks.length + x.possible_policy_shocks.length || 'None'}</td></tr>)}</tbody></table></div></section>}</section> }
function JourneyView({ journey }: { journey: Journey | null }) { return <section className="page-content">{journey ? <><PageHeading step="05 / PLAN" title={journey.title} text={`${journey.condition} / care journey`} /><div className="timeline">{journey.events.map((x) => <article className="event" key={x.id}><span className="event-dot" /><small>{x.occurred_on} / {x.status}</small><strong>{x.title}</strong><span>{x.event_type}</span></article>)}</div><button className="secondary">+ Add care event</button></> : <Empty text="No care journey is available for the selected patient." />}</section> }
function Copilot({ question, setQuestion, answer, evidence, ask }: { question: string; setQuestion: (x: string) => void; answer: string; evidence: unknown[]; ask: (e: FormEvent) => void }) { const faqs = ['Why was this hospital recommended?', 'What does the policy cover?', 'What should I confirm before treatment?']; return <section className="page-content"><div className="copilot"><PageHeading step="06 / ASK" title="Caregiver Copilot" text="Ask about a decision using the selected CogniCare records." /><div className="faq-strip"><span className="eyebrow">COMMON QUESTIONS</span><div>{faqs.map((faq) => <button key={faq} type="button" onClick={() => setQuestion(faq)}>{faq}</button>)}</div></div><form className="copilot-form" onSubmit={ask}><input required minLength={3} value={question} onChange={(e) => setQuestion(e.target.value)} placeholder="Ask about this decision..." /><button className="primary">Ask Copilot <span>→</span></button></form>{answer && <div className="copilot-answer"><span className="eyebrow">ANSWER</span><p>{answer}</p><div className="source-list"><span className="eyebrow">SUPPORTING DATA</span>{evidence.map((item, i) => <details key={i}><summary>Evidence source</summary><p>{JSON.stringify(item)}</p></details>)}</div></div>}</div></section> }
function Emergency({ hospitals, selected, select, load }: { hospitals: EmergencyHospital[]; selected: EmergencyHospital | null; select: (x: EmergencyHospital) => void; load: () => void }) { return <section className="page-content"><PageHeading step="EMERGENCY ACCESS" title="Emergency care" text="Insurance policy is advisory and should never block emergency care." action={<button className="emergency-button" onClick={load}>Find nearby care</button>} />{hospitals.length ? <div className="match-layout"><div className="hospital-list">{hospitals.map((x) => <button className="hospital-card" key={x.hospital_id} onClick={() => select(x)}><span className="rank-number">0{x.emergency_rank}</span><div><h3>{x.hospital_name}</h3><div className="card-meta"><b>{x.distance_km ?? '—'} km</b><span>{x.emergency_capable ? 'Emergency capable' : 'Capability unavailable'}</span></div></div></button>)}</div><MapView hospitals={hospitals} selected={selected} select={(item) => select(item as EmergencyHospital)} /></div> : <Empty text="Use Find nearby care to load emergency-capable hospitals." />}</section> }
function Empty({ text }: { text: string }) { return <div className="empty"><strong>No data yet</strong><p>{text}</p></div> }
export default App
